# Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [33]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.28404921 0.84769514 0.83040111 0.63943484]
 [0.35863419 0.01718657 0.45996249 0.1323171 ]
 [0.53616599 0.12945866 0.10769821 0.81223977]
 [0.36043516 0.83675147 0.50477546 0.36126714]
 [0.9850263  0.73417852 0.3576464  0.38418197]
 [0.44208956 0.26463707 0.57447879 0.38364309]
 [0.97860936 0.31513299 0.68460788 0.61647994]
 [0.43609872 0.23051155 0.31519263 0.04098768]
 [0.44295128 0.76464256 0.5530644  0.99282576]
 [0.24689236 0.74291406 0.20192339 0.61664756]]
First 5 rows of the above array:
[[0.28404921 0.84769514 0.83040111 0.63943484]
 [0.35863419 0.01718657 0.45996249 0.1323171 ]
 [0.53616599 0.12945866 0.10769821 0.81223977]
 [0.36043516 0.83675147 0.50477546 0.36126714]
 [0.9850263  0.73417852 0.3576464  0.38418197]]


# Write a Pandas program to select the rows where the number of attempts in the examination is
greater than 2.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Expected Output:
Number of attempts in the examination is greater than 2:
name score attempts qualify
b Dima 9.0 3 no
d James NaN 3 no
f Michael 20.0 3 yes

In [12]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Number of attempts in the examination is greater than 2  :")
print(df[(df['attempts'] > 2)]) 

Number of attempts in the examination is greater than 2  :
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


# From the sample data given in TASK 2; write a program to calculate the average of the scores. The
program should be able to ignore NaN values.
Expected Output:
The average score is : 13.56

In [34]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
# print("Number of attempts in the examination is greater than 2  :")
# print(df[(df['attempts'] > 2)])
df['score'] = df['score'].fillna(0)
print(df.score)
print(df.score.mean())

a    12.5
b     9.0
c    16.5
d     0.0
e     9.0
f    20.0
g    14.5
h     0.0
i     8.0
j    19.0
Name: score, dtype: float64
10.85
