In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data=pd.read_csv(r'iris_data_2a.csv')
print(data.head())


   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0


In [2]:
x=data.drop('species','columns')
y=data['species']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
scaler=StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [3]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [4]:
print(x_train)


[[ 1.03735427  0.61128752  1.07780765  1.16191108]
 [-1.83435866 -0.33217875 -1.38629846 -1.36591074]
 [ 0.41306885 -0.33217875  0.27554055  0.09756505]
 [ 0.66278302 -0.56804532  1.02050286  1.29495434]
 [-0.08635948 -0.80391189  0.73397889  0.89582458]
 [ 0.28821177 -0.56804532  0.10362617  0.09756505]
 [-0.46093074 -1.27564503  0.10362617  0.09756505]
 [-0.58578782  0.84715409 -1.21438408 -1.36591074]
 [-0.96035907  0.61128752 -1.21438408 -0.96678098]
 [ 0.28821177 -1.03977846  1.02050286  0.23060831]
 [-0.46093074 -1.74737816  0.10362617  0.09756505]
 [ 1.03735427  0.13955439  0.33284534  0.23060831]
 [ 1.66163969  0.37542096  1.24972203  0.76278132]
 [-0.33607365 -0.09631218  0.39015013  0.36365156]
 [ 0.28821177 -0.09631218  0.61936931  0.76278132]
 [-0.33607365 -0.80391189  0.21823575  0.09756505]
 [ 0.0384976  -0.09631218  0.21823575  0.36365156]
 [-0.21121657  3.20581978 -1.32899367 -1.09982423]
 [ 0.66278302  0.37542096  0.84858848  1.42799759]
 [-1.21007324 -0.09631218 -1.38

In [5]:
print(x_test)

[[-1.33493032  0.84715409 -1.09977449 -1.36591074]
 [-1.45978741  0.37542096 -1.27168887 -1.36591074]
 [-0.96035907 -1.27564503 -0.46942177 -0.16852145]
 [ 0.78764011 -0.09631218  1.13511245  1.29495434]
 [ 0.16335469 -0.33217875  0.39015013  0.36365156]
 [ 1.91135386 -0.56804532  1.30702683  0.89582458]
 [-1.83435866 -0.09631218 -1.44360325 -1.36591074]
 [-0.96035907  1.08302066 -1.38629846 -1.23286749]
 [ 1.28706844  0.37542096  1.07780765  1.42799759]
 [ 0.41306885 -1.98324473  0.39015013  0.36365156]
 [ 0.0384976   0.37542096  0.56206451  0.76278132]
 [-0.46093074  2.73408664 -1.38629846 -1.36591074]
 [-1.08521616  1.31888723 -1.38629846 -1.36591074]
 [-1.83435866  0.37542096 -1.44360325 -1.36591074]
 [ 1.03735427  0.13955439  0.50475972  0.36365156]
 [-1.08521616 -1.74737816 -0.29750739 -0.30156471]
 [ 1.03735427 -1.27564503  1.13511245  0.76278132]
 [-0.96035907  1.79062037 -1.27168887 -1.36591074]
 [ 1.28706844  0.13955439  0.90589327  1.16191108]
 [-0.21121657 -1.03977846 -0.18

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
result= regressor.predict(x_test)
print("Result:\n",result)

Result:
 [ 7.47530970e-02  2.46988924e-02  8.82387939e-01  2.01892053e+00
  1.34980992e+00  1.79338088e+00  6.08184499e-04 -2.26178909e-02
  1.99851153e+00  1.34860880e+00  1.60817994e+00 -1.61270522e-01
 -7.51368900e-02 -6.46677869e-03  1.29860333e+00  9.10592301e-01
  1.76279138e+00 -4.84529908e-02  1.80801157e+00  8.55848228e-01
  1.78478169e-02  1.32160552e+00  1.45584457e-01  2.10792002e+00
  1.05673675e+00 -8.30606942e-02 -5.76733698e-02  1.77092328e+00
  1.18304838e+00  1.82517150e+00]


In [7]:
# Evaluating Model's Performance
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('Mean Absolute Error:', mean_absolute_error(y_test, result))
print('Mean Squared Error:', mean_squared_error(y_test, result))
print('Mean Root Squared Error:', np.sqrt(mean_squared_error(y_test, result)))


Mean Absolute Error: 0.14679953904513843
Mean Squared Error: 0.03963542531588112
Mean Root Squared Error: 0.19908647697892773
